In [1]:
import pandas as pd
import numpy as np

### IMPORT FILE 
#### df1 = ไฟล์ก่อน
#### df2 = ไฟล์หลัง

In [2]:
df1 = pd.read_excel('before.xlsx', skiprows = 12)
df1.head()

,Unnamed: 0,Title,Authors,Year,Scopus Source title,Volume,Issue,Pages,Citations
0,1.0,Auditor Independence and Audit Quality: A Lite...,"Tepalagul, N., Lin, L.",2015.0,"Journal of Accounting, Auditing and Finance",30,1,101-121,43.0
1,2.0,A novel architecture for requirement-oriented ...,"Xu, L.D., Viriyasitavat, W.",2014.0,IEEE Transactions on Industrial Informatics,10,2,1478-1485,41.0
2,3.0,Compliance checking for requirement-oriented s...,"Viriyasitavat, W., Xu, L.D., Viriyasitavat, W.",2014.0,IEEE Transactions on Industrial Informatics,10,2,1469-1477,36.0
3,4.0,The societal relevance of management accountin...,"Chiwamit, P., Modell, S., Yang, C.L.",2014.0,Accounting and Business Research,44,2,144-180,31.0
4,5.0,Revenue maximization with a single sample,"Dhangwatnotai, P., Roughgarden, T., Yan, Q.",2015.0,Games and Economic Behavior,91,-,318-333,29.0

In [3]:
df2 = pd.read_excel('after.xls', skiprows = 12)
df2.tail()

,Title,Authors,Year,Scopus Source title,Volume,Issue,Pages,Citations
197,Managing QoS of Internet-of-Things Services Us...,"Viriyasitavat, W., Xu, L.D., Bi, Z., Hoonsopon...",2019.0,IEEE Transactions on Computational Social Systems,6,6,1357-1368,0.0
198,Combining geographic information system (GIS) ...,"Setamanit, S.-O., Aemon, K.",2018.0,"Journal of Telecommunication, Electronic and C...",10,3,123-127,0.0
199,Competition and profits in the airline industr...,"Eng, L.L., Vichitsarawong, T.",2019.0,International Journal of Revenue Management,11,1-2,126-150,0.0
200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,© 2020 Elsevier B.V. All rights reserved. SciV...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### FILTER COLUMN

In [4]:
df_before = df1[['Title','Citations']]
df_before.tail()

                                                 Title  Citations
193  Combining geographic information system (GIS) ...        0.0
194  Adoption of mobile banking services: An empiri...        0.0
195  Supporting the understanding investor behavior...        0.0
196                                                NaN        NaN
197  © 2019 Elsevier B.V. All rights reserved. SciV...        NaN

In [5]:
df_after = df2[['Title','Citations']]
df_after.tail()

                                                 Title  Citations
197  Managing QoS of Internet-of-Things Services Us...        0.0
198  Combining geographic information system (GIS) ...        0.0
199  Competition and profits in the airline industr...        0.0
200                                                NaN        NaN
201  © 2020 Elsevier B.V. All rights reserved. SciV...        NaN

### LEFT JOIN
#### AFTER LEFT JOIN WITH BEFORE

In [6]:
result = pd.merge(df_after, df_before, how = 'left', on = 'Title' )
result.columns = ['Title', 'Citations_after', 'Citations_before']
result['Change'] = result['Citations_after'] - result['Citations_before']
result.fillna(0, inplace = True)
result

,Title,Citations_after,Citations_before,Change
0,Auditor Independence and Audit Quality: A Lite...,44.0,43.0,1.0
1,A novel architecture for requirement-oriented ...,42.0,41.0,1.0
2,Compliance checking for requirement-oriented s...,37.0,36.0,1.0
3,The societal relevance of management accountin...,31.0,31.0,0.0
4,A new approach for compliance checking in serv...,30.0,28.0,2.0
...,...,...,...,...
197,Managing QoS of Internet-of-Things Services Us...,0.0,0.0,0.0
198,Combining geographic information system (GIS) ...,0.0,0.0,0.0
199,Competition and profits in the airline industr...,0.0,0.0,0.0
200,0,0.0,0.0,0.0
201,© 2020 Elsevier B.V. All rights reserved. SciV...,0.0,0.0,0.0

#### DROP TWO LAST ROWS

In [7]:
result.drop(result.tail(2).index,inplace=True)
result.tail()

,Title,Citations_after,Citations_before,Change
195,Information quality of e-commerce websites: Ch...,0.0,0.0,0.0
196,Adoption of mobile banking services: An empiri...,0.0,0.0,0.0
197,Managing QoS of Internet-of-Things Services Us...,0.0,0.0,0.0
198,Combining geographic information system (GIS) ...,0.0,0.0,0.0
199,Competition and profits in the airline industr...,0.0,0.0,0.0

#### FIND A MONTH

In [8]:
month = pd.read_excel('after.xls', skiprows= 6)
month = month.iloc[1,1]

In [9]:
print(month)

9 January 2020

### FILTER TITLE AND MONTH

In [10]:
ending_result = result[['Title', 'Change']]
ending_result.columns = ['Title', month]
ending_result

                                                 Title  9 January 2020
0    Auditor Independence and Audit Quality: A Lite...             1.0
1    A novel architecture for requirement-oriented ...             1.0
2    Compliance checking for requirement-oriented s...             1.0
3    The societal relevance of management accountin...             0.0
4    A new approach for compliance checking in serv...             2.0
..                                                 ...             ...
195  Information quality of e-commerce websites: Ch...             0.0
196  Adoption of mobile banking services: An empiri...             0.0
197  Managing QoS of Internet-of-Things Services Us...             0.0
198  Combining geographic information system (GIS) ...             0.0
199  Competition and profits in the airline industr...             0.0

[200 rows x 2 columns]

#### CHANGE ROW INDEX

In [11]:
ending_result.index = range(1,len(ending_result)+1)
ending_result

                                                 Title  9 January 2020
1    Auditor Independence and Audit Quality: A Lite...             1.0
2    A novel architecture for requirement-oriented ...             1.0
3    Compliance checking for requirement-oriented s...             1.0
4    The societal relevance of management accountin...             0.0
5    A new approach for compliance checking in serv...             2.0
..                                                 ...             ...
196  Information quality of e-commerce websites: Ch...             0.0
197  Adoption of mobile banking services: An empiri...             0.0
198  Managing QoS of Internet-of-Things Services Us...             0.0
199  Combining geographic information system (GIS) ...             0.0
200  Competition and profits in the airline industr...             0.0

[200 rows x 2 columns]

In [12]:
Change_in_month = ending_result.to_excel('result.xlsx')